"""create a table

Revision ID: 95b66bee0bc8
Revises: 1943733ccdb6
Create Date: 2025-06-02 12:47:09.356568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b66bee0bc8'
down_revision: Union[str, None] = '1943733ccdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('posts', 'image_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_file', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
